<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0rkan45\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0rkan45/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0rkan45.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0rkan45\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0rkan45\appProdProjectContainer([
    'container.build_hash' => '0rkan45',
    'container.build_id' => 'f4368eb8',
    'container.build_time' => 1627383318,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0rkan45');
